"""Error name tokens for REP-0158 compliance checks.

Centralizes check IDs so that renumbering a REP section only requires
updating this file. Check code and tests both import from here.
"""

# §1.1 — Coordinate Systems & Units
WRONG_METERS_PER_UNIT = "1.1.1"
WRONG_KILOGRAMS_PER_UNIT = "1.1.2"
WRONG_UP_AXIS = "1.1.3"
ROOT_HAS_ROTATION = "1.1.4"
WRONG_TIME_CODES_PER_SECOND = "1.1.5"
KINEMATIC_TRANSFORM_OPS = "1.1.6"
KINEMATIC_NON_IDENTITY_SCALE = "1.1.7"

# §1.2 — Asset Structure & Composition
MISSING_DEFAULT_PRIM = "1.2.1"
MISSING_ASSET_IDENTIFIER = "1.2.2"
MISSING_ASSET_VERSION = "1.2.3"
ABSOLUTE_OR_PROPRIETARY_PATH = "1.2.4"
NESTED_COMPONENT = "1.2.6"
VARIANT_NO_DEFAULT = "1.2.7"
INHERITS_SPECIALIZES_ARC = "1.2.8"
CUSTOM_COMPOSITION_ATTR = "1.2.9"
PAYLOAD_GATES_KINEMATIC = "1.2.10"
POINT_INSTANCER_PHYSICS = "1.2.11"
SCHEMA_LAYER_BINARY = "1.2.12"
HEAVY_LAYER_ASCII = "1.2.13"

# §1.3 — Physics
MISSING_JOINT_LIMITS = "1.3.1"
MULTIPLE_ARTICULATION_ROOTS = "1.3.2"
NON_POSITIVE_MASS = "1.3.3"
COLLISION_GEOMETRY_AUTHORING = "1.3.4"
COLLISION_MISSING_MATERIAL = "1.3.5"
MIMIC_JOINT_CONSTRAINT = "1.3.7"
INSTANCEABLE_PHYSICS = "1.3.8"
MIMIC_JOINT_DEPRECATED = "1.3.9"

# §2.1 — ROS Context
CONTEXT_INSIDE_PAYLOAD = "2.1.1"
NESTED_CONTEXT_PARENT_FRAME = "2.1.2"
INVALID_CONTEXT_NAMESPACE = "2.1.3"

# §2.2 — ROS Interface Placement & Structure
INTERFACE_INSIDE_PAYLOAD = "2.2.1"
INTERFACE_ON_RIGID_BODY = "2.2.2"
MULTIPLE_INTERFACES_PER_PRIM = "2.2.3"
SENSOR_NOT_DIRECT_XFORM_CHILD = "2.2.4"

# §2.3 — ROS Naming
INVALID_ROS_NAME = "2.3.1"

# §2.4 — ROS Topic
MISSING_TOPIC_ROLE = "2.4.1"
MISSING_TOPIC_NAME = "2.4.2"
MISSING_TOPIC_TYPE = "2.4.3"
MISSING_PUBLISH_RATE = "2.4.4"
INVALID_QOS_TOKEN = "2.4.5"
INVALID_STARTS_ENABLED = "2.4.6"
INVALID_OVERRIDE_FRAME_ID = "2.4.7"
INVALID_MATCH_PUBLISHER = "2.4.8"
INVALID_QOS_DEPTH = "2.4.9"

# §2.5 — ROS Service
MISSING_SERVICE_ATTR = "2.5.1"
INVALID_SERVICE_STARTS_ENABLED = "2.5.2"

# §2.6 — ROS Action
MISSING_ACTION_ATTR = "2.6.1"
INVALID_ACTION_STARTS_ENABLED = "2.6.2"

# §2.7 — ROS Frame
FRAME_ON_RIGID_BODY = "2.7.1"
INVALID_FRAME_ID = "2.7.2"
INVALID_FRAME_STATIC = "2.7.3"

# §2.8 — Camera Optical Frame
CAMERA_OPTICAL_FRAME = "2.8.1"

# §2.9 — Prohibited Interfaces
PROHIBITED_TOPIC_NAME = "2.9.1"
PROHIBITED_INTERFACE_TYPE = "2.9.2"

# §2.10 — Joint Name
MISSING_JOINT_NAME = "2.10.1"

# §3.1 — Material Portability
MISSING_PREVIEW_SURFACE = "3.1.1"
UDIM_TEXTURE = "3.1.2"

# §3.2 — Texture Format
FORBIDDEN_TEXTURE_FORMAT = "3.2.1"
DATA_MAP_JPEG = "3.2.2"

# §3.3 — Texture Baking
PROCEDURAL_SHADER = "3.3.1"

# §3.4 — Geometry Constraints
COLLISION_NOT_TRIANGULATED = "3.4.1"
LEFT_HANDED_ORIENTATION = "3.4.2"
DOUBLE_SIDED_MESH = "3.4.3"

# §3.6 — Lighting Portability
COMPLEX_AREA_LIGHT = "3.6.1"

# §4.2 — Extended Physics
MIMIC_WRONG_JOINT_TYPE = "4.2.1"
MIMIC_INVALID_RELATIONSHIP = "4.2.2"
MIMIC_CYCLE = "4.2.3"
ACTUATOR_INVALID_TARGETS = "4.2.4"
CLAMPING_LOOKUP_TABLE = "4.2.5"
